substitutions:
  name: apollo-esk-1
  version: "25.1.29.1"
  device_description: ${name} made by Apollo Automation - version ${version}.

esphome:
  name: "${name}"
  friendly_name: Apollo ESK-1
  comment: Apollo ESK-1 Starter Kit
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.ESK-1"
    version: "${version}"

  min_version: 2023.11.1

  on_shutdown:
    - light.turn_off: rgb_light
    - switch.turn_off: accessory_power

  on_boot:
    - priority: 500
      then:
        - lambda: |-
            id(deep_sleep_1).set_sleep_duration(id(deep_sleep_sleep_duration).state * 60 * 60 * 1000);
        - if:
            condition:
              or:
                - binary_sensor.is_on: ota_mode
                - switch.is_on: prevent_sleep
            then:
              - lambda: |-
                  ESP_LOGW("Apollo", "Preventing Deep Sleep Due To OTA On Boot");
                  id(deep_sleep_1).prevent_deep_sleep();

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf

external_components:
  - source: github://ApolloAutomation/esphome-battery-component
    components: [max17048]

api:
  id: api_server
  reboot_timeout: 0s
  on_client_connected:
    then:
      - delay: 5s
      - if:
          condition:
            or:
              - binary_sensor.is_on: ota_mode
              - switch.is_on: prevent_sleep
          then:
            - lambda: |-
                ESP_LOGW("Apollo", "Preventing Deep Sleep Due To OTA Or Switch");
                id(deep_sleep_1).prevent_deep_sleep();
          else:
            - lambda: |-
                id(reportAllValues).execute();
            - delay: 2s
            - deep_sleep.enter:
                id: deep_sleep_1

#########
######### Buzzer Module Start
#########
  services:
    - service: play_buzzer
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

output:
  - platform: ledc
    pin: GPIO18
    id: buzzer
rtttl:
  id: rtttl_buzzer
  output: buzzer
#########
######### Buzzer Module End
#########

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ap:
    ssid: "Apollo ESK-1 Hotspot"

logger:

captive_portal:

i2c:
  #- id: i2c_bus_1
  #  sda: GPIO21
  #  scl: GPIO20
  - id: i2c_bus_2
    sda: GPIO1
    scl: GPIO0


one_wire:
  - platform: gpio
    pin: GPIO6

deep_sleep:
  id: deep_sleep_1
  sleep_duration: 24h
  run_duration: 90s

number:
  - platform: template
    name: "Sleep Duration"
    id: deep_sleep_sleep_duration
    min_value: 0
    max_value: 800
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 24
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG
    unit_of_measurement: "h"
    on_value:
      then:
        - lambda: |-
            id(deep_sleep_1).set_sleep_duration(x * 60 * 60 * 1000);

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

  - platform: homeassistant
    name: "OTA Mode"
    id: ota_mode
    entity_id: input_boolean.apollo_ota_mode
    on_press:
      then:
        - lambda: |-
            id(deep_sleep_1).prevent_deep_sleep();
    on_release:
      then:
        - if:
            condition:
              switch.is_off: prevent_sleep
            then:
              - lambda: |-
                  id(deep_sleep_1).allow_deep_sleep();
#########
######### PIR Module Start
#########

  - platform: gpio
    name: "PIR"
    pin:
      number: GPIO3
      mode:
        input: true
        pulldown: false
    id: io_pir
    device_class: motion

#########
######### PIR Module End
#########

#########
######### Button Module Start
#########

#  -   platform: gpio
#      id: button_1
#      name: "Button 1"
#      pin:
#        number: GPIO6
#        mode:
#          input: true
#          pullup: true
#        inverted: true
#      on_press:
#        then:
#          - logger.log: "Button 1 pressed"

#########
######### Button Module End
#########

sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature
    disabled_by_default: true

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

#########
######### AHT Module Start
#########
  - platform: aht10
    variant: AHT20
    id: aht_20
    temperature:
      name: "Temperature"
      id: aht_temperature
    humidity:
      name: "Humidity"
      id: aht_humidity
    update_interval: 60s

#########
######### AHT Module End
#########

#########
######### SHT30 Module Start
#########
  - platform: sht3xd
    id: sht30
    temperature:
      name: "SHT Temperature"
      id: sht_temperature
    humidity:
      name: "SHT Relative Humidity"
      id: sht_humidity
    update_interval: 60s
    i2c_id: i2c_bus_2
#########
######### SHT30 Module End
#########

#########
######### SEN55 Module Start
#########
  - platform: sen5x
    id: sen55
    pm_1_0:
      name: "PM <1µm Weight Concentration"
      id: pm_1_0
      accuracy_decimals: 1
    pm_2_5:
      name: "PM <2.5µm Weight Concentration"
      id: pm_2_5
      accuracy_decimals: 1
    pm_4_0:
      name: "PM <4µm Weight Concentration"
      id: pm_4_0
      accuracy_decimals: 1
    pm_10_0:
      name: "PM <10µm Weight Concentration"
      id: pm_10_0
      accuracy_decimals: 1
    temperature:
      name: "SEN55 Temperature"
      id: sen55_temperature
      accuracy_decimals: 1
    humidity:
      name: "SEN55 Humidity"
      id: sen55_humidity
      accuracy_decimals: 1
    voc:
      name: "SEN55 VOC"
      id: sen55_voc
    nox:
      name: "SEN55 NOX"
      id: sen55_nox
    acceleration_mode: low
    store_baseline: true
    address: 0x69
    update_interval: 10s
    i2c_id: i2c_bus_2
#########
######### SEN55 Module End
#########

#########
######### BMI160 Module Start
#########
  - platform: bmi160
    id: bmi160_imu
    address: 0x68
    i2c_id: i2c_bus_2
    update_interval: 60s
    acceleration_x:
      name: "Acceleration X"
      id: accel_x
    acceleration_y:
      name: "Acceleration Y"
      id: accel_y
    acceleration_z:
      name: "Acceleration Z"
      id: accel_z
    gyroscope_x:
      name: "Gyroscope X"
      id: gyro_x
    gyroscope_y:
      name: "Gyroscope Y"
      id: gyro_y
    gyroscope_z:
      name: "Gyroscope Z"
      id: gyro_z
    temperature:
      name: "BMI160 Temperature"
      id: bmi160_temperature
#########
######### BMI160 Module End
#########

#########
######### MiCS Module Start
#########
  - platform: mics_4514
    id: mics4514
    nitrogen_dioxide:
      name: Nitrogen Dioxide
    carbon_monoxide:
      name: Carbon Monoxide
    hydrogen:
      name: Hydrogen
    ethanol:
      name: Ethanol
    methane:
      name: Methane
    ammonia:
      name: Ammonia
    update_interval: 10s
    i2c_id: i2c_bus_2
#########
######### MiCS Module End
#########

#########
######### Dallas Probe Module Start
#########
  - platform: dallas_temp
    name: "Temperature Probe"
    id: temp_probe
    update_interval: 60s
#########
######### Dallas Probe Module End
#########

  - platform: max17048
    id: max_17048
    battery_voltage:
      name: Battery Voltage
      id: batt_v
    battery_level:
      name: Battery Level
      id: batt_pct
      filters:
        - lambda: |
            if (x > 100) return 100;
            else return (x);

switch:
  - platform: template
    name: "Prevent Sleep"
    id: prevent_sleep
    icon: mdi:sleep
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    entity_category: "config"
    on_turn_on:
      then:
        - lambda: |-
            id(deep_sleep_1).prevent_deep_sleep();
    on_turn_off:
      then:
        - if:
            condition:
              binary_sensor.is_off: ota_mode
            then:
              - lambda: |-
                  id(deep_sleep_1).allow_deep_sleep();

  - platform: factory_reset
    id: factory_reset_switch
    disabled_by_default: true

  - platform: gpio
    pin: GPIO4
    name: "Accessory Power"
    id: accessory_power
    restore_mode: ALWAYS_ON
    setup_priority: 2000

    internal: true

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

light:
  - platform: esp32_rmt_led_strip
    id: rgb_light
    name: "RGB Board Light"
    pin: GPIO5
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rmt_symbols: 48
    rgb_order: grb

#########
######### LED Module Start
#########
  - platform: esp32_rmt_led_strip
    id: rgb_module
    name: "RGB Module Light"
    pin: GPIO14
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 10
    rmt_symbols: 48
    rgb_order: grb

#########
######### LED Module End
#########



script:
  - id: reportAllValues
    then:
      - component.update: wifi_signal_db
      - component.update: sys_esp_temperature
      - component.update: sys_uptime
      - component.update: sht30
      - component.update: sen55
      - component.update: mics4514
      - component.update: bmi160_imu
      - component.update: temp_probe
      - component.update: max_17048
